import type { RoomBase } from "./raumplan_positions";

// Hier pflegst du die statischen Raeume ohne Kalender-Anbindung.
// Diese Overlays zeigen nur den Namen und koennen farbig oder transparent hinterlegt werden.
export const leereRaeume: RoomBase[] = [
  {
    id: "raum-leer-kueche",
    name: "Küche",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#7c2d12",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(251, 191, 36, 0.22)",
    overlayBorderColor: "#d97706",
    overlayBorderWidth: "2px",
    top: 1121,
    left: 2329,
    width: 301,
    height: 85,
  },
  {
    id: "raum-leer-lounge-foyer",
    name: "Lounge Foyer",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#7c2d12",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(251, 191, 36, 0.22)",
    overlayBorderColor: "#d97706",
    overlayBorderWidth: "2px",
    top: 820,
    left: 2690,
    width: 310,
    height: 250,
  },
{
    id: "raum-leer-Open Office",
    name: "Open Office",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#7c2d12",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(251, 191, 36, 0.22)",
    overlayBorderColor: "#d97706",
    overlayBorderWidth: "2px",
    top: 273,
    left: 3145,
    width: 367,
    height: 174,
  },
  {
    id: "raum-leer-Open Space",
    name: "Open Space",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#7c2d12",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(251, 191, 36, 0.22)",
    overlayBorderColor: "#d97706",
    overlayBorderWidth: "2px",
    top: 273,
    left:2807,
    width: 325,
    height: 190,
  },

  {
    id: "raum-leer-Kapele",
    name: "Kapelle",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#7c2d12",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(251, 191, 36, 0.22)",
    overlayBorderColor: "#d97706",
    overlayBorderWidth: "2px",
    top: 561,
    left: 2765,
    width: 110,
    height: 168,
  },


        {
    id: "raum-leer-kueche-ost",
    name: "Küche",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#7c2d12",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(251, 191, 36, 0.22)",
    overlayBorderColor: "#d97706",
    overlayBorderWidth: "2px",
    top: 1811,
    left: 2946,
    width: 85,
    height: 108,
  },
    {
    id: "raum-leer-foyer-ost",
    name: "Foyer Ost",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#7c2d12",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(251, 191, 36, 0.22)",
    overlayBorderColor: "#d97706",
    overlayBorderWidth: "2px",
    top: 1731,
    left: 3127,
    width: 425,
    height: 140,
  },
  {
    id: "raum-leer-dachterrasse",
    name: "Dachterrasse",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#7c2d12",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(251, 191, 36, 0.22)",
    overlayBorderColor: "#d97706",
    overlayBorderWidth: "2px",
    top: 1143,
    left: 3383,
    width: 230,
    height: 580,
  },
    {
    id: "raum-leer-WC-D",
    name: "WC D",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#020202",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(227, 93, 189, 0.3)",
    overlayBorderColor: "rgba(227, 93, 189, 0.3)",
    overlayBorderWidth: "2px",
    top: 510,
    left: 497,
    width: 126,
    height: 160,
  },
      {
    id: "raum-leer-WC-D-zusatz",
    name: " ",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "rgba(227, 93, 189, 0.3)",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(227, 93, 189, 0.3)",
    overlayBorderColor: "rgba(227, 93, 189, 0.3)",
    overlayBorderWidth: "2px",
    top: 510,
    left: 621,
    width: 39,
    height: 65,
  },
      {
    id: "raum-leer-WC-D-Ost",
    name: "WC D",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#020202",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(227, 93, 189, 0.3)",
    overlayBorderColor: "rgba(227, 93, 189, 0.3)",
    overlayBorderWidth: "2px",
    top: 1968,
    left: 1181,
    width: 136,
    height: 110,
  },
      {
    id: "raum-leer-WC-H",
    name: "WC H",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(58, 149, 223, 0.22)",
    overlayBorderColor: "rgba(58, 149, 223, 0.22)",
    overlayBorderWidth: "1px",
    top: 510,
    left: 676,
    width: 70,
    height: 160,
  },
        {
    id: "raum-leer-WC-H-zusatz",
    name: " ",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(58, 149, 223, 0.22)",
    overlayBorderColor: "rgba(58, 149, 223, 0.22)",
    overlayBorderWidth: "2px",
    top: 580,
    left: 628,
    width: 49,
    height: 89,
  },
     {
    id: "raum-leer-WC-H-Ost",
    name: "WC H",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(58, 149, 223, 0.22)",
    overlayBorderColor: "rgba(58, 149, 223, 0.22)",
    overlayBorderWidth: "2px",
    top: 1968,
    left: 1323,
    width: 165,
    height: 110,
  },
     {
    id: "raum-leer-WC-B-Ost",
    name: "WC B",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(58, 223, 215, 0.22)",
    overlayBorderColor: "rgba(58, 223, 215, 0.22)",
    overlayBorderWidth: "2px",
    top: 1968,
    left: 1490,
    width: 100,
    height: 110,
  },

  // Vorlage fuer weitere leere Raeume:
  // {
  //   id: "raum-leer-neu",
  //   name: "Neuer Raum",
  //   bookedBy: "",
  //   showCalendarInfo: false,
  //   status: "free",
  //   time: "",
  //   labelPosition: "inside",
  //   labelColor: "#111111",
  //   nameFontSize: "24px",
  //   overlayGroundColor: "rgba(255, 255, 255, 0.08)",
  //   overlayBorderColor: "#666666",
  //   overlayBorderWidth: "2px",
  //   top: 1200,
  //   left: 900,
  //   width: 180,
  //   height: 90,
  // },
];
