import type { RoomBase } from "./raumplan_positions";

// Hier pflegst du die statischen Raeume ohne Kalender-Anbindung.
// Diese Overlays zeigen nur den Namen und koennen farbig oder transparent hinterlegt werden.
export const leereRaeume: RoomBase[] = [
  {
    id: "raum-leer-kueche",
    name: "Küche",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(247, 247, 247, 0.54)",
    overlayBorderColor: "#000000",
    overlayBorderWidth: "2px",
    top: 1120,
    left: 2328,
    width: 303,
    height: 85,
  },
  {
    id: "raum-leer-lounge-foyer",
    name: "Lounge Foyer",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(247, 247, 247, 0.54)",
    overlayBorderColor: "#000000",
    overlayBorderWidth: "2px",
    top: 820,
    left: 2690,
    width: 310,
    height: 250,
  },
{
    id: "raum-leer-Open Space",
    name: "Open Space",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(247, 247, 247, 0.54)",
    overlayBorderColor: "#000000",
    overlayBorderWidth: "2px",
    top: 273,
    left: 3148,
    width: 363,
    height: 174,
  },
  {
    id: "raum-leer-Open Office",
    name: "Open Office",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(247, 247, 247, 0.54)",
    overlayBorderColor: "#000000",
    overlayBorderWidth: "2px",
    top: 273,
    left:2807,
    width: 323,
    height: 190,
  },

  {
    id: "raum-leer-Kapele",
    name: "Kapelle",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(247, 247, 247, 0.54)",
    overlayBorderColor: "#000000",
    overlayBorderWidth: "2px",
    top: 561,
    left: 2765,
    width: 110,
    height: 169,
  },


        {
    id: "raum-leer-kueche-ost",
    name: "Küche",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(247, 247, 247, 0.54)",
    overlayBorderColor: "#000000",
    overlayBorderWidth: "2px",
    top: 1811,
    left: 2946,
    width: 104,
    height: 108,
  },
    {
    id: "raum-leer-foyer-ost",
    name: "Foyer Ost",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(247, 247, 247, 0.54)",
    overlayBorderColor: "#000000",
    overlayBorderWidth: "2px",
    top: 1728,
    left: 3127,
    width: 425,
    height: 150,
  },
  {
    id: "raum-leer-dachterrasse",
    name: "Dachterrasse",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(247, 247, 247, 0.54)",
    overlayBorderColor: "#000000",
    overlayBorderWidth: "2px",
    top: 1143,
    left: 3380,
    width: 236,
    height: 578,
  },
    {
    id: "raum-leer-WC-D",
    name: "WC D",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#020202",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(183, 171, 217, 0.82)",
    overlayBorderColor: "rgba(183, 171, 217, 0.82)",
    overlayBorderWidth: "0px",
    top: 582,
    left: 2393,
    width: 117,
    height: 148,
  },
      {
    id: "raum-leer-WC-D-zusatz",
    name: " ",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "rgba(227, 93, 189, 0.3)",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(183, 171, 217, 0.82)",
    overlayBorderColor: "rgba(183, 171, 217, 0.82)",
    overlayBorderWidth: "0px",
    top: 582,
    left: 2510,
    width: 44,
    height: 59,
  },
      {
    id: "raum-leer-WC-D-Ost",
    name: "WC D",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#020202",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(183, 171, 217, 0.82)",
    overlayBorderColor: "rgba(183, 171, 217, 0.82)",
    overlayBorderWidth: "2px",
    top: 1925,
    left: 3026,
    width: 121,
    height: 101,
  },
      {
    id: "raum-leer-WC-H",
    name: "WC H",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(183, 171, 217, 0.82)",
    overlayBorderColor: "rgba(183, 171, 217, 0.82)",
    overlayBorderWidth: "0px",
    top: 582,
    left: 2558,
    width: 66,
    height: 146,
  },
        {
    id: "raum-leer-WC-H-zusatz",
    name: " ",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(183, 171, 217, 0.82)",
    overlayBorderColor: "rgba(183, 171, 217, 0.82)",
    overlayBorderWidth: "0px",
    top: 647,
    left: 2514,
    width: 44,
    height: 81,
  },
     {
    id: "raum-leer-WC-H-Ost",
    name: "WC H",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(183, 171, 217, 0.82)",
    overlayBorderColor: "rgba(183, 171, 217, 0.82)",
    overlayBorderWidth: "2px",
    top: 1925,
    left: 3154,
    width: 149,
    height: 101,
  },
     {
    id: "raum-leer-WC-B-Ost",
    name: "WC B",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(139, 121, 188, 0.82)",
    overlayBorderColor: "rgba(139, 121, 188, 0.82)",
    overlayBorderWidth: "2px",
    top: 1925,
    left: 3309,
    width: 93,
    height: 101,
  },

  // Vorlage fuer weitere leere Raeume:
  // {
  //   id: "raum-leer-neu",
  //   name: "Neuer Raum",
  //   bookedBy: "",
  //   showCalendarInfo: false,
  //   status: "free",
  //   time: "",
  //   labelPosition: "inside",
  //   labelColor: "#111111",
  //   nameFontSize: "24px",
  //   overlayGroundColor: "rgba(255, 255, 255, 0.08)",
  //   overlayBorderColor: "#666666",
  //   overlayBorderWidth: "2px",
  //   top: 1200,
  //   left: 900,
  //   width: 180,
  //   height: 90,
  // },
];
