import type { RoomBase } from "./raumplan_positions";

// Hier pflegst du die statischen Raeume ohne Kalender-Anbindung.
// Diese Overlays zeigen nur den Namen und koennen farbig oder transparent hinterlegt werden.
export const leereRaeume: RoomBase[] = [
  {
    id: "raum-leer-kueche",
    name: "Küche",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#7c2d12",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(251, 191, 36, 0.22)",
    overlayBorderColor: "#d97706",
    overlayBorderWidth: "2px",
    top: 1118,
    left: 478,
    width: 285,
    height: 80,
  },
  {
    id: "raum-leer-lounge-foyer",
    name: "Lounge Foyer",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#7c2d12",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(251, 191, 36, 0.22)",
    overlayBorderColor: "#d97706",
    overlayBorderWidth: "2px",
    top: 811,
    left: 810,
    width: 305,
    height: 258,
  },
{
    id: "raum-leer-Open Office",
    name: "Open Office",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#7c2d12",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(251, 191, 36, 0.22)",
    overlayBorderColor: "#d97706",
    overlayBorderWidth: "2px",
    top: 315,
    left: 921,
    width: 650,
    height: 185,
  },

  {
    id: "raum-leer-Kapele",
    name: "Kapelle",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#7c2d12",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(251, 191, 36, 0.22)",
    overlayBorderColor: "#d97706",
    overlayBorderWidth: "2px",
    top: 590,
    left: 895,
    width: 105,
    height: 159,
  },

    {
    id: "raum-leer-ruhe-office",
    name: "Ruhe Office",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#7c2d12",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(251, 191, 36, 0.22)",
    overlayBorderColor: "#d97706",
    overlayBorderWidth: "2px",
    top: 743,
    left: 209,
    width: 210,
    height: 144,
  },
        {
    id: "raum-leer-kueche-ost",
    name: "Küche",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#7c2d12",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(251, 191, 36, 0.22)",
    overlayBorderColor: "#d97706",
    overlayBorderWidth: "2px",
    top: 1772,
    left: 1064,
    width: 80,
    height: 105,
  },
    {
    id: "raum-leer-foyer-ost",
    name: "Foyer Ost",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#7c2d12",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(251, 191, 36, 0.22)",
    overlayBorderColor: "#d97706",
    overlayBorderWidth: "2px",
    top: 1693,
    left: 1245,
    width: 390,
    height: 136,
  },
  {
    id: "raum-leer-dachterrasse",
    name: "Dachterrasse",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#7c2d12",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(251, 191, 36, 0.22)",
    overlayBorderColor: "#d97706",
    overlayBorderWidth: "2px",
    top: 1142,
    left: 1475,
    width: 222,
    height: 545,
  },
    {
    id: "raum-leer-WC-D",
    name: "WC D",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#020202",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(227, 93, 189, 0.3)",
    overlayBorderColor: "rgba(227, 93, 189, 0.3)",
    overlayBorderWidth: "2px",
    top: 610,
    left: 541,
    width: 110,
    height: 138,
  },
      {
    id: "raum-leer-WC-D-zusatz",
    name: " ",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "rgba(227, 93, 189, 0.3)",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(227, 93, 189, 0.3)",
    overlayBorderColor: "rgba(227, 93, 189, 0.3)",
    overlayBorderWidth: "2px",
    top: 610,
    left: 651,
    width: 42,
    height: 55,
  },
      {
    id: "raum-leer-WC-D-Ost",
    name: "WC D",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#020202",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(227, 93, 189, 0.3)",
    overlayBorderColor: "rgba(227, 93, 189, 0.3)",
    overlayBorderWidth: "2px",
    top: 1880,
    left: 1139,
    width: 115,
    height: 100,
  },
      {
    id: "raum-leer-WC-H",
    name: "WC H",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(58, 149, 223, 0.22)",
    overlayBorderColor: "rgba(58, 149, 223, 0.22)",
    overlayBorderWidth: "1px",
    top: 610,
    left: 692,
    width: 67,
    height: 138,
  },
        {
    id: "raum-leer-WC-H-zusatz",
    name: " ",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(58, 149, 223, 0.22)",
    overlayBorderColor: "rgba(58, 149, 223, 0.22)",
    overlayBorderWidth: "2px",
    top: 670,
    left: 656,
    width: 37,
    height: 79,
  },
     {
    id: "raum-leer-WC-H-Ost",
    name: "WC H",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(58, 149, 223, 0.22)",
    overlayBorderColor: "rgba(58, 149, 223, 0.22)",
    overlayBorderWidth: "2px",
    top: 1880,
    left: 1259,
    width: 130,
    height: 100,
  },
     {
    id: "raum-leer-WC-B-Ost",
    name: "WC B",
    bookedBy: "",
    showCalendarInfo: false,
    status: "free",
    time: "",
    labelPosition: "inside",
    labelColor: "#000000",
    nameFontSize: "24px",
    overlayGroundColor: "rgba(58, 223, 215, 0.22)",
    overlayBorderColor: "rgba(58, 223, 215, 0.22)",
    overlayBorderWidth: "2px",
    top: 1880,
    left: 1400,
    width: 99,
    height: 100,
  },

  // Vorlage fuer weitere leere Raeume:
  // {
  //   id: "raum-leer-neu",
  //   name: "Neuer Raum",
  //   bookedBy: "",
  //   showCalendarInfo: false,
  //   status: "free",
  //   time: "",
  //   labelPosition: "inside",
  //   labelColor: "#111111",
  //   nameFontSize: "24px",
  //   overlayGroundColor: "rgba(255, 255, 255, 0.08)",
  //   overlayBorderColor: "#666666",
  //   overlayBorderWidth: "2px",
  //   top: 1200,
  //   left: 900,
  //   width: 180,
  //   height: 90,
  // },
];
